server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/user_db
    username: springuser
    password: ThePassword
  jpa.hibernate.ddl-auto: update

  #   url: jdbc:h2:mem:testdb
  #   driverClassName: org.h2.Driver
  #   username: user
  #   password: password
  # jpa.database-platform: org.hibernate.dialect.H2Dialect

  # h2.console.enabled: true
springdoc:
  swagger-ui:
    path: /api-doc